# -*- coding: utf-8 -*-
"""Lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLVACwAPYma2ONiwwSrhGHqdoocMP13F

[NEURAL NETWORK](https://playground.tensorflow.org/#activation=tanh&batchSize=10&dataset=circle&regDataset=reg-plane&learningRate=0.03&regularizationRate=0&noise=0&networkShape=4,4,7,6,2&seed=0.39129&showTestData=false&discretize=false&percTrainData=50&x=true&y=true&xTimesY=false&xSquared=false&ySquared=false&cosX=false&sinX=false&cosY=false&sinY=false&collectStats=false&problem=classification&initZero=false&hideText=false)

---

Activaciones
"""

import numpy as np
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

np.random.seed(42)

# ==========================================================
# ACTIVACIONES
# ==========================================================

class ReLU:
    @staticmethod
    def forward(x):
        return np.maximum(0, x)

    @staticmethod
    def derivative(x):
        return (x > 0).astype(float)


class LeakyReLU:
    @staticmethod
    def forward(x, alpha=0.01):
        return np.where(x > 0, x, alpha * x)

    @staticmethod
    def derivative(x, alpha=0.01):
        return np.where(x > 0, 1.0, alpha)


class Sigmoid:
    @staticmethod
    def forward(x):
        x = np.clip(x, -500, 500)
        return 1 / (1 + np.exp(-x))

    @staticmethod
    def derivative(x):
        s = Sigmoid.forward(x)
        return s * (1 - s)


class Tanh:
    @staticmethod
    def forward(x):
        return np.tanh(x)

    @staticmethod
    def derivative(x):
        return 1 - np.tanh(x) ** 2


class Softmax:

    @staticmethod
    def forward(x):

        # estabilidad numérica
        x = x - np.max(x)

        exp_x = np.exp(x)

        return exp_x / np.sum(exp_x)

    @staticmethod
    def derivative(x):
        raise NotImplementedError(
            "Softmax se usa junto con CrossEntropy."
        )


ACTIVACIONES = {
    "relu": ReLU,
    "leaky_relu": LeakyReLU,
    "sigmoide": Sigmoid,
    "tanh": Tanh,
    "softmax": Softmax
}

# ==========================================================
# FUNCIONES DE PÉRDIDA
# ==========================================================

class MSE:
    @staticmethod
    def loss(y_true, y_pred):
        return 0.5 * np.sum((y_true - y_pred) ** 2) / len(y_true)

    @staticmethod
    def derivative(y_true, y_pred):
        return (y_pred - y_true) / len(y_true)

class CrossEntropy:

    @staticmethod
    def loss(y_true, y_pred):

        y_pred = np.clip(
            y_pred,
            1e-15,
            1 - 1e-15
        )

        return -np.sum(
            y_true * np.log(y_pred)
        )

    @staticmethod
    def derivative(y_true, y_pred):

        y_pred = np.clip(
            y_pred,
            1e-15,
            1 - 1e-15
        )

        return y_pred - y_true

PERDIDAS = {
    "mse": MSE,
    "cross_entropy": CrossEntropy
}

# ==========================================================
# RED NEURONAL
# ==========================================================

class RedNeuronal:

    def __init__(
        self,
        capas,
        activaciones,
        perdida="mse",
        init="he",
        optimizer="sgd"
    ):

        if len(activaciones) != len(capas) - 1:
            raise ValueError(
                "Debe existir una activación por cada capa de salida."
            )

        self.capas = capas
        self.activaciones = activaciones
        self.perdida = perdida
        self.optimizer = optimizer
        self.pesos = []
        self.historial_loss = []
        self.historial_precision = []

        # momentos para Adam
        self.m_w = []
        self.v_w = []
        self.adam_t = 0

        print("\n==============================")
        print("CREANDO RED NEURONAL")
        print("Capas:", capas)
        print("Activaciones:", activaciones)
        print("Pérdida:", perdida)
        print("Init:", init)
        print("Optimizador:", optimizer)

        for i in range(len(capas) - 1):

            esc = (
                np.sqrt(2.0 / capas[i])   # He   — bueno para ReLU
                if init == "he"
                else np.sqrt(1.0 / capas[i])  # Xavier — bueno para sigmoid/tanh
            )

            w = np.random.randn(capas[i] + 1, capas[i + 1]) * esc

            self.pesos.append(w)
            self.m_w.append(np.zeros_like(w))
            self.v_w.append(np.zeros_like(w))

    # ------------------------------------------------------

    def agregarBias(self, x):
        return np.insert(x, 0, 1)

    # ------------------------------------------------------

    def forwardPropagating(self, entradas):

        activacion = self.agregarBias(
            entradas.astype(float)
        )

        activaciones = [activacion]
        nets = []

        for idx, pesos in enumerate(self.pesos):

            net = pesos.T @ activacion
            nets.append(net)

            nombre_act = self.activaciones[idx]
            funcion = ACTIVACIONES[nombre_act]

            activacion = funcion.forward(net)

            if idx < len(self.pesos) - 1:
                activacion = self.agregarBias(
                    activacion
                )

            activaciones.append(activacion)

        return activaciones, nets

    # ------------------------------------------------------

    def backwardPropagating(
        self,
        activaciones,
        nets,
        objetivo,
        lr=0.01
    ):

        salida = activaciones[-1]

        perdida = PERDIDAS[self.perdida]

        error_salida = perdida.derivative(
            objetivo,
            salida
        )

        deltas = [None] * len(self.pesos)

        if (
            self.activaciones[-1] == "softmax"
            and
            self.perdida == "cross_entropy"
        ):

            deltas[-1] = error_salida

        else:

            ultima_activacion = ACTIVACIONES[
                self.activaciones[-1]
            ]

            deltas[-1] = (
                error_salida
                * ultima_activacion.derivative(
                    nets[-1]
                )
            )

        for l in range(
            len(self.pesos) - 2,
            -1,
            -1
        ):

            pesos_sig = self.pesos[l + 1]

            delta_prop = (
                pesos_sig[1:]
                @ deltas[l + 1]
            )

            activacion_actual = ACTIVACIONES[
                self.activaciones[l]
            ]

            deltas[l] = (
                delta_prop
                * activacion_actual.derivative(
                    nets[l]
                )
            )

        if self.optimizer == "sgd":

            for l in range(len(self.pesos)):

                gradiente = (
                    activaciones[l].reshape(-1, 1)
                    @ deltas[l].reshape(1, -1)
                )

                self.pesos[l] -= lr * gradiente

        else:
            # Adam
            beta1, beta2, eps = 0.9, 0.999, 1e-8
            self.adam_t += 1

            for l in range(len(self.pesos)):

                gradiente = (
                    activaciones[l].reshape(-1, 1)
                    @ deltas[l].reshape(1, -1)
                )

                self.m_w[l] = beta1 * self.m_w[l] + (1 - beta1) * gradiente
                self.v_w[l] = beta2 * self.v_w[l] + (1 - beta2) * gradiente ** 2

                m_hat = self.m_w[l] / (1 - beta1 ** self.adam_t)
                v_hat = self.v_w[l] / (1 - beta2 ** self.adam_t)

                self.pesos[l] -= lr * m_hat / (np.sqrt(v_hat) + eps)

        return perdida.loss(
            objetivo,
            salida
        )

    # ------------------------------------------------------

    def entrenar(
        self,
        X,
        y,
        epocas=10,
        lr=0.01,
        batch_log=1
    ):

        print("\n==============================")
        print("INICIANDO ENTRENAMIENTO")
        print("Muestras:", len(X))

        N = len(X)
        indices = np.arange(N)

        for epoca in range(epocas):

            np.random.shuffle(indices)

            error_total = 0

            for i in indices:

                acts, nets = (
                    self.forwardPropagating(X[i])
                )

                error_total += (
                    self.backwardPropagating(
                        acts,
                        nets,
                        y[i],
                        lr
                    )
                )

            error_promedio = error_total / N

            correctos = sum(
                np.argmax(self.predecir(X[i])) == np.argmax(y[i])
                for i in range(N)
            )

            precision = correctos / N * 100

            self.historial_loss.append(error_promedio)
            self.historial_precision.append(precision)

            if (epoca + 1) % batch_log == 0:
                print(
                    f"Época {epoca+1:3d} "
                    f"| Error: {error_promedio:.6f} "
                    f"| Precisión: {precision:.2f}%"
                )

    # ------------------------------------------------------

    def predecir(self, entradas):

        activaciones, _ = (
            self.forwardPropagating(
                np.array(entradas)
            )
        )

        return activaciones[-1]

class VisualizadorRedNeuronal:

    def __init__(self, red):
        self.red = red

    # =====================================================
    # Mostrar ejemplos aleatorios o consecutivos
    # =====================================================

    def mostrar_predicciones(
        self,
        X,
        y,
        cantidad=10
    ):

        filas = 2
        columnas = int(np.ceil(cantidad / filas))

        fig, axes = plt.subplots(
            filas,
            columnas,
            figsize=(12, 6)
        )

        axes = np.array(axes).ravel()

        for i in range(cantidad):

            imagen = X[i].reshape(28, 28)

            pred = self.red.predecir(X[i])

            digito_predicho = np.argmax(pred)

            color = (
                "green"
                if digito_predicho == y[i]
                else "red"
            )

            axes[i].imshow(
                imagen,
                cmap="gray"
            )

            axes[i].axis("off")

            axes[i].set_title(
                f"Pred: {digito_predicho}\nReal: {y[i]}",
                color=color
            )

        plt.tight_layout()
        plt.show()

    # =====================================================
    # Mostrar solamente errores
    # =====================================================

    def mostrar_errores(
        self,
        X,
        y,
        cantidad=10
    ):

        errores = []

        for idx in range(len(X)):

            pred = self.red.predecir(X[idx])

            digito_predicho = np.argmax(pred)

            if digito_predicho != y[idx]:

                errores.append(
                    {
                        "indice": idx,
                        "imagen": X[idx].reshape(
                            28,
                            28
                        ),
                        "pred": digito_predicho,
                        "real": y[idx]
                    }
                )

        print(
            f"Errores encontrados: {len(errores)}"
        )

        if len(errores) == 0:

            print(
                "No se encontraron errores."
            )

            return

        cantidad = min(
            cantidad,
            len(errores)
        )

        filas = 2
        columnas = int(np.ceil(cantidad / filas))

        fig, axes = plt.subplots(
            filas,
            columnas,
            figsize=(12, 6)
        )

        axes = np.array(axes).ravel()

        for i in range(len(axes)):

            if i >= cantidad:
                axes[i].axis("off")
                continue

            err = errores[i]

            axes[i].imshow(
                err["imagen"],
                cmap="gray"
            )

            axes[i].axis("off")

            axes[i].set_title(
                f"ID:{err['indice']}\n"
                f"Pred:{err['pred']}\n"
                f"Real:{err['real']}",
                color="red"
            )

        plt.tight_layout()
        plt.show()

    def mostrar_aprendizaje(self):

        fig, axes = plt.subplots(
            1,
            2,
            figsize=(12, 4)
        )

        axes[0].plot(
            self.red.historial_loss
        )

        axes[0].set_title(
            "Pérdida"
        )

        axes[0].set_xlabel(
            "Época"
        )

        axes[0].set_ylabel(
            "Loss"
        )

        axes[1].plot(
            self.red.historial_precision
        )

        axes[1].set_title(
            "Precisión"
        )

        axes[1].set_xlabel(
            "Época"
        )

        axes[1].set_ylabel(
            "%"
        )

        plt.tight_layout()
        plt.show()

    def matriz_confusion(
        self,
        X,
        y
    ):

        matriz = np.zeros(
            (10, 10),
            dtype=int
        )

        for xi, yi in zip(X, y):

            pred = np.argmax(
                self.red.predecir(xi)
            )

            matriz[yi][pred] += 1

        plt.figure(figsize=(8, 8))

        plt.imshow(
            matriz,
            cmap="Blues"
        )

        plt.colorbar()

        plt.xlabel(
            "Predicción"
        )

        plt.ylabel(
            "Real"
        )

        plt.title(
            "Matriz de Confusión"
        )

        for i in range(10):
            for j in range(10):

                plt.text(
                    j,
                    i,
                    matriz[i, j],
                    ha="center",
                    va="center"
                )

        plt.show()
# ==========================================================
# CARGA DE DATOS MNIST
# ==========================================================

print("Cargando MNIST...")

(X_train_raw, y_train_raw), \
(X_test_raw, y_test_raw) = mnist.load_data()

N_ENTRENAMIENTO = 3000
N_PRUEBA = 1000

X_train = X_train_raw[:N_ENTRENAMIENTO]
y_train = y_train_raw[:N_ENTRENAMIENTO]

X_test = X_test_raw[:N_PRUEBA]
y_test = y_test_raw[:N_PRUEBA]

X_train = (
    X_train.reshape(-1, 784) / 255.0
)

X_test = (
    X_test.reshape(-1, 784) / 255.0
)

y_train_onehot = np.eye(10)[y_train]
y_test_onehot = np.eye(10)[y_test]

# ==========================================================
# CONFIGURACIÓN DE LA RED
# ==========================================================

red = RedNeuronal(
    capas=[784, 64, 32, 10],
    activaciones=[
        "leaky_relu",
        "leaky_relu",
        "softmax"
    ],
    perdida="cross_entropy",
    init="he",
    optimizer="sgd"
)
# ==========================================================
# ENTRENAMIENTO
# ==========================================================

red.entrenar(
    X_train,
    y_train_onehot,
    epocas=70,
    lr=0.001,
    batch_log=1
)

# ==========================================================
# EVALUACIÓN
# ==========================================================

print("\n==============================")
print("EVALUACIÓN")

correctos = 0

for xi, yi in zip(X_test, y_test):

    pred = red.predecir(xi)

    if np.argmax(pred) == yi:
        correctos += 1

precision = (
    correctos / len(X_test)
) * 100

print(
    f"Precisión en prueba: "
    f"{precision:.2f}%"
)

print("\nMuestras:")

for i in range(10):

    pred = red.predecir(X_test[i])

    print(
        f"Imagen {i:2d} "
        f"| Pred: {np.argmax(pred)} "
        f"| Real: {y_test[i]}"
    )


visualizador = VisualizadorRedNeuronal(red)

visualizador.mostrar_predicciones(
    X_test,
    y_test
)

visualizador.mostrar_errores(
    X_test,
    y_test
)

visualizador.mostrar_aprendizaje()

visualizador.matriz_confusion(
    X_test,
    y_test
)
